build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/dockerfile-validator
  commands:
    - wget https://github.com/UKHomeOffice/dockerfile-validator/releases/download/v0.1.0/dockerfile-validatorlinux_amd64
    - chmod a+x dockerfile-validatorlinux_amd64
    - ./dockerfile-validatorlinux_amd64 -r rules.yaml

publish:
  docker:
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    # environment:
    #   - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/deep-ui
    storage_driver: vfs
    tag:
      - latest
      - v0.0.$$BUILD_NUMBER
    when:
      branch: master

    branch: master

# deploy:
#   kubernetes:
#     image: quay.io/ukhomeofficedigital/drone-kubernetes
#     registry: quay.io
#     replicationcontrollers:
#       - kubernetes/deep-web-rc.yaml
#     services:
#      - kubernetes/deep-web-svc.yaml
#     token: $$TOKEN
#     apiserver: https://54.194.108.241
#     namespace: default
#     debug: true
#     tag: v0.0.$$BUILD_NUMBER
