debug: true

publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/deep-ui
    storage_driver: vfs
    tag:
      - latest
      - v0.0.$$BUILD_NUMBER
    when:
      branch: master

    branch: master

deploy:
  kubernetes:
    image: quay.io/ukhomeofficedigital/drone-kubernetes
    registry: quay.io
    replicationcontrollers:
      - kubernetes/deep-web-rc.yaml
    services: []
    token: $$TOKEN
    apiserver: https://54.194.108.241
    namespace: default
    debug: true
    tag: v0.0.$$BUILD_NUMBER
