
publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/deep-ui
    storage_driver: vfs
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master

    branch: master

deploy:
  kubernetes:
    image: quay.io/ukhomeofficedigital/drone-kubernetes
    registry: quay.io
    replicationcontrollers:
      - kubernetes/deep-web-rc.yaml
    services: []
    token: $$TOKEN
    apiserver: https://kubeapi-dev.dsp.notprod.homeoffice.gov.uk:6443
    namespace: default
    debug: true
