apiVersion: v1
kind: Service
metadata:
  name: deep-web-svc
  labels:
    name: deep-web-svc
    deep: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    deep: web
