apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deep-web
    deep: web
  name: deep-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: deep-web
    spec:
      containers:
      - image: quay.io/ukhomeofficedigital/deep-ui:{{ .TAG }}
        name: deep-web
        ports:
        - name: deep-web
          containerPort: 80
